FROM golang:1.19.4-alpine as builder
RUN apk add --no-cache make gcc musl-dev linux-headers git
WORKDIR /go-ethereum
COPY ./l2geth/go.mod ./l2geth/go.sum ./
RUN go mod download
ADD ./l2geth ./
RUN make geth

FROM alpine:3.16
RUN apk add --no-cache ca-certificates jq curl
COPY --from=builder /go-ethereum/build/bin/geth /usr/local/bin/
EXPOSE 8545 8546 8547
COPY ./ops/scripts/geth.sh .
ENTRYPOINT ["sh", "./geth.sh"]
